### ISSUE TITLE
Уточнение постановки задачи 

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-5-excel#1]
Необходимо сформулировать общее представление о проекте — как будет выглядеть электронная таблица и какими функциями она будет обладать. Полученное представление следует описать в README.md в виде одного или нескольких абзацев. После этого данную задачу можно закрывать.

**Comment by kupihleba** [comment]
**Браузерная версия excel**
Задача:
Создать программу для работы с электронными таблицами.

Базовая программа должна поддерживать следующие возможности:
- Изменение размеров таблицы
- Редактирование содержимого ячеек. Смена цвета, стиля, размера шрифта
- Поддержка формул https://bit.ly/2uKHRuz
- Обработка рекурсивных зависимостей в формулах

Также планируется реализовать:
- Сохранение и экспорт таблицы на локальный компьютер
- Удобную навигация по таблице (поиск данных, фильтры)
- CSS анимация

Опционально:
- Сохранение данных на сервер
- Аккаунты для хранения таблиц на сервере
- Мобильная версия сайта
- Встраивание графиков _(Google Charts никто не запрещал:)_

> Язык реализации: JavaScript (Без использования фреймворков, jQuery. Допускается использование AJAX для обмена данными с сервером)
> Требования к коду: https://www.w3schools.com/js/js_conventions.asp, комментарии на английском языке. _(+ см почту)_
> Соблюдаем принципы ООП (инкапсуляция, наследование, полиморфизм, абстракция). MVC.

**Comment by Mazdaywik** [comment]
Отлично! Надеюсь, остальные последуют вашему примеру.
