### ISSUE TITLE
Баги парсера

### ISSUE THREAD

**Issue by SimpleCreations** [bmstu-iu9/utp2017-5-excel#11]
* Пустая формула (если набрать просто знак `=` в ячейку) не должна вызывать ошибку. Значение в событии должно быть `undefined`.
* При парсинге токенов нужно проверять все символы. Некорректные символы должны вызывать синтаксическую ошибку. Сейчас если набрать `=1.5`, в парсере возникнет неперехваченное исключение

**Comment by Alex13658** [comment]
Баги исправлены
