### ISSUE TITLE
Ещё баги парсера

### ISSUE THREAD

**Issue by SimpleCreations** [bmstu-iu9/utp2017-5-excel#12]
* Не работают строки в формуле. Например, если набрать `="abc"`, значение в поле `expression` будет пустое.
* Поле `position` в классе `_Expression` должно быть числом.
* Некорректно обрабатываются ссылки на ячейку. Воспроизводим:
    1. Пишем в ячейку B1: `=1`
    2. Пишем в ячейку A1: `=B1`

**Comment by Alex13658** [comment]
Баги исправлены
