### ISSUE TITLE
Диапазоны

### ISSUE THREAD

**Issue by SimpleCreations** [bmstu-iu9/utp2017-5-excel#15]
Нужно добавить поддержку диапазонов как типа значений в формуле.
Пример использования: `=CONCATENATE("Сумма: ", STRING(SUM(A1:A10)))`

* Добавляем токен `:` (`COLON`)
* Создаём класс `Spreadsheet._Range`:
  * поле `start` типа `Spreadsheet._CellReference` — ссылка на первую угловую ячейку диапазона
  * поле `end` типа `Spreadsheet._CellReference` — ссылка на противоположную угловую ячейку
  * метод `forEachCell(callback)` вызвает функцию `callback` для каждой ячейки из диапазона, начиная с левой верхней и двигаясь справа налево, сверху вниз. `callback(cell, row, column)` вызывается с параметрами:
    * `cell` типа `Spreadsheet._Cell` — ячейка;
    * `row`, `column` -- координаты этой ячейки.
* Обновлеяем парсер с учётом новой грамматики
* В evaluate аналогично `CellReference` должна быть проверка, что все ячейки из диапазона существуют и определены
* Пишем тестовую функцию SUM, код который примерно следующий:
  ```javascript
  SUM(...args) {
      // Проверяем: количество args должно быть >= 1
      return args.reduce((sum, element) => {
            if (element instanceof Spreadsheet.Table) {
                  let rangeSum = 0;
                  element.forEachValue(cell => {
                        // Проверяем, что значение cell — number
                        rangeSum += cell.value;
                  });
                  return sum + rangeSum;
            } else if (typeof element === "number") {
                  return sum + element;
            } else {
                  // Ошибка
            }
      }, 0);
  }
  ```

**Comment by Alex13658** [comment]
Выполнено
