### ISSUE TITLE
Относительные и абсолютные адреса ячеек

### ISSUE THREAD

**Issue by SimpleCreations** [bmstu-iu9/utp2017-5-excel#16]
Нужно добавить поддержку относительных и абсолютных адресов строк и столбцов ячеек.
Адрес абсолютный, если он не меняется при копировании или перемещении ячейки.
Если адрес строки или столбца абсолютный, перед индексом стоит символ `$`. Например, `$A1`, `A$1`, `$A$1`

* Добавляем токены: `FUNCTION`, `CELL_REFERENCE`.
  * Если токен, который раньше был `IDENTIFIER`, может представлять собой **только** функцию, тогда этот токен записывается как `FUNCTION`. Пример: `SUM`, `STRING`, `LOLOLOLOL`, `A01`
  * Если токен, который раньше был `IDENTIFIER`, может представлять собой **только** ссылку на ячейку, то этот токен записывается как `CELL_REFERENCE`. Пример: `$A1`, `A$99`, `$ZZ$666`
  * Если на этапе лексического анализа нельзя определить, является токен ссылкой на ячейку или функцией, он записывается как `IDENTIFIER`. Примеры: `A1`, `ZZ666`, `LOG10`
* Как следствие, `$` входит в токен `CELL_REFERENCE` (или `IDENTIFIER` согласно грамматике). Некорректные записи вроде `A$B1`, `$$A1`, `A1$` должны вызывать синтаксическую ошибку.
* При парсинге если ссылка на ячейку содержит абсолютный адрес, нужно устанавливать свойства соответствующего объекта класса `Spreadsheet._CellReference` соответственно `rowFixed = true | false`, `columnFixed = true | false`

**Comment by Alex13658** [comment]
Немного иначе реализована поддержка абсолютных адресов.
