### ISSUE TITLE
Копирование ячейки

### ISSUE THREAD

**Issue by SimpleCreations** [bmstu-iu9/utp2017-5-excel#17]
Предварительно должна быть выполнена задача об относительных и абсолютных адресах строк и столбцов ячеек.

* Реализуем метод `move(fromRow, fromColumn, toRow, toColumn)` класса `Spreadsheet._CellReference`. Он возвращает новый `Spreadsheet._CellReference`, в котором:
  * Если в исходной ссылке строка не фиксированная, индекс строки изменён на `toRow - fromRow`;
  * Если в исходной ссылке столбец не фиксированный, индекс столбца изменён на `toColumn - fromColumn`;
  * `rowFixed` и `columnFixed` имеют такие же значения.
* Переопределяем метод `toString` класса `Spreadsheet._Expression`. Это метод "собирает" разобранное выражение обратно в строку-формулу.
* Определяем метод `generateFormula` класса `Spreadsheet._Cell`. Он преобразует поле `expression` в строку и кладёт её в `formula`.
* Разделяем метод `setFormula` на два: `setFormula(i, j, formula)` и `setExpression(i, j, expression)`. Второй устанавливает пропарсенное выражение и используется в первом.
* Реализуем метом `copyCell(fromRow, fromColumn, toRow, toColumn)` класса `Spreadsheet`. Он копирует `expression` из ячейки с первыми координатами рекурсивно, заменяя все `_CellReference` на `.move(fromRow, fromColumn, toRow, toColumn)`, в ячейку со вторыми координатами. Затем вызывает `generateFormula` последней. Затем вызывает `setExpression(toRow, toColumn, expression)`.

**Comment by Alex13658** [comment]
Добавлено
