### ISSUE TITLE
Разработка архитектуры проекта и распределение ролей

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-5-excel#2]
Требуется разработать архитектуру электронной таблицы:
* выбрать подходы и технологии, которые будут использоваться при разработке, а именно паттерны проектирования;
* определить, из каких крупных компонентов будет состоять решение;
* распределить обязанности участников между различными компонентами и различными видами деятельности, создав на каждую подзадачу «issue» и назначив её на участника.

**Comment by kupihleba** [comment]
- В качестве паттерна был выбран Model-View-Controller _(MVC)_

- **Задачи**:
> 1. Создать дизайн, модель сайта - _View_  
> @SimpleCreations, @jkhizbullina 

> 2. Реализовать интерфейс взаимодействия модели с view - _Controller_
> @Imwritingcrapcode 

> 3. Реализовать структуру данных таблица - _Model_
 3.1 В виде двумерного массива
 3.2 В виде оптимизированной структуры данных
>  @kir4567, @Iheiko,

> 4. Реализовать поддержку формул
> @crusty7, @Iheiko
