### ISSUE TITLE
Model: Базовая структура данных

### ISSUE THREAD

**Issue by kupihleba** [bmstu-iu9/utp2017-5-excel#4]
**Задача: разработать структуру данных таблица**
-
Разработать структуру данных таблица, реализованную в виде двумерного массива.
Создать методы:
- Изменяющие данные в клетках таблицы
- Возвращающие значение клетки, в случае, если в ней не записана формула
- Изменяющие размер таблицы
- Очищающие таблицу

**Comment by Alex13658** [comment]
3-4 пункты выполнены. 1-2 отпадают в связи ненадобностью.
